yrdif_blog_post:
    resource: "@YrdifBlogBundle/Resources/config/routing/post.yml"
    prefix:   /posts

yrdif_blog_contact-request:
    resource: "@YrdifBlogBundle/Resources/config/routing/contactrequest.yml"
    prefix:   /contact

yrdif_blog_homepage:
    path:     /
    defaults: { _controller: YrdifBlogBundle:Page:index }
    methods: GET

yrdif_blog_about:
    path:     /about
    defaults: { _controller: YrdifBlogBundle:Page:about }
    methods: GET
